# Generated by Django 4.2 on 2023-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('modelo', models.CharField(max_length=20, verbose_name='Ano')),
                ('data_compra', models.DateField(verbose_name='Data de compra')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='Cpf')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_nacimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=200, verbose_name='Ano')),
            ],
        ),
    ]
