# Generated by Django 4.2 on 2023-05-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('data_aluguel', models.DateField(verbose_name='Data de aluguel')),
                ('data_devolucao', models.DateField(verbose_name='Data de devolução')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('devolucao', models.BooleanField(verbose_name='Devolvido')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carro_alugueis', to='aluguel.carro', verbose_name='Carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_alugueis', to='aluguel.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
