# Generated by Django 4.2 on 2023-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
