# Generated by Django 4.2 on 2023-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_carro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=20, verbose_name='Modelo'),
        ),
    ]
